- .eslintrc
- README.md
- assets/linting.css
- karma.conf.js
- lib/modeler/Linting.js
- lib/modeler/LintingAnnotations.js
- lib/modeler/index.js
- modeler.js
- package-lock.json
- package.json
- properties-panel.js
- test/helper.js
- test/spec/Linter.spec.js
- test/spec/modeler/Linting.spec.js
- test/spec/modeler/LintingAnnotations.spec.js
- test/spec/modeler/linting.bpmn
- test/spec/utils/properties-panel.spec.js
- test/suite.js
* add linting annotations to canvas
* add single API to update both annotations and properties panel errors
---
Related to https://github.com/bpmn-io/internal-docs/issues/591
> Add Annotations

- CHANGELOG.md
* `FEAT`: add bpmn-js plugin for canvas and properties panel errors ([#11](https://github.com/camunda/linting/pull/11))
* `FEAT`: add no-zeebe-properties rule ([#43](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/43))
> chore(CHANGELOG): update to v0.5.0-alpha.0

- karma.conf.js
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/camunda-cloud-1-0-valid.bpmn
- test/spec/camunda-cloud-1-1-valid.bpmn
- test/spec/camunda-cloud-1-2-valid.bpmn
- test/spec/camunda-cloud-1-3-valid.bpmn
- test/spec/camunda-cloud-8-0-valid.bpmn
- test/spec/camunda-cloud-8-1-valid.bpmn
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3084
Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/45 to be merged and integrated.
> Adjust timer event definition error messages

- CHANGELOG.md
- lib/Linter.js
- lib/utils/error-messages.js
- test/spec/utils/error-messages.spec.js
> fix(error-messages): support Camunda Versions >8.0

- package-lock.json
- package.json
Related to https://github.com/camunda/camunda-modeler/issues/3246
> deps: update bpmn-js-properties-panel dependency

- assets/linting.css
- lib/modeler/LintingAnnotations.js
- test/spec/modeler/Linting.spec.js
- test/spec/modeler/LintingAnnotations.spec.js
- test/spec/modeler/linting.bpmn
* adds linting annotations for warnings
---
Related to https://github.com/camunda/camunda-modeler/issues/3200
> feat: show lint error and warning annotations

- lib/Linter.js
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
* incorporates https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/50 and hints at the allowed version if it exists
---
Related to https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/50
> Error Message Hints at Allowed Version

- lib/utils/error-messages.js
- test/spec/utils/error-messages.spec.js
Related to https://github.com/bpmn-io/internal-docs/issues/644.
> chore: add collapsed subprocess error message

- lib/Linter.js
- lib/utils/error-messages.js
- lib/utils/version.js
- test/spec/utils/error-messages.spec.js
Related to https://github.com/camunda/camunda-modeler/pull/3279
> fix: handle minor and patch versions when getting label

- .github/workflows/CI.yml
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
> Support FEEL expression in Script Task

- CHANGELOG.md
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/camunda-cloud-8-1-errors.bpmn
- test/spec/camunda-cloud-8-2.bpmn
- test/spec/utils/properties-panel.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3319
> Bump `bpmnlint-plugin-camunda-compat`

- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3318
> Escalation support + error code adjustment

- CHANGELOG.md
- package-lock.json
- package.json
Related to https://github.com/camunda/camunda-modeler/issues/3368
> Skip non executable process

- CHANGELOG.md
- lib/utils/error-messages.js
- test/spec/utils/error-messages.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3443
> fix: display error message for disallowed FEEL error code

- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
* adjust `signal-reference` error messages
---
Closes https://github.com/camunda/linting/issues/52
> feat: adjust `signal-reference` error messages

- CHANGELOG.md
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/99
Related to https://github.com/camunda/camunda-modeler/issues/3653
> Fix timer error message

- CHANGELOG.md
- package-lock.json
- package.json
- test/spec/Linter.spec.js
- test/spec/camunda-platform-7-20-errors.bpmn
- test/spec/camunda-platform-7-20.bpmn
Related to https://github.com/camunda/camunda-modeler/issues/3632
> feat: integrate platform 7.20 rules

- CHANGELOG.md
- lib/Linter.js
- test/spec/Linter.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3637
> feat: report rule name

- CHANGELOG.md
- lib/Linter.js
- lib/modeler/Linting.js
- lib/utils/properties-panel.js
- test/spec/utils/properties-panel.spec.js
related to https://github.com/bpmn-io/bpmn-js-element-templates/pull/3#discussion_r1241888309
> chore: persist all entryIds in the report

- lib/modeler/Linting.js
- lib/utils/properties-panel.js
- test/spec/modeler/Linting.spec.js
- test/spec/utils/properties-panel.spec.js
related to https://github.com/camunda/camunda-modeler/issues/3712
> chore: add history TTL property panel entry

- lib/compiled-config.js
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
related to https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/106
> feat: integrate start form rule

- lib/Linter.js
- lib/utils/documentation.js
- test/spec/Linter.spec.js
- test/spec/utils/documentation.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3609
Related to https://github.com/camunda/camunda-modeler/pull/3713
> Add Documentation URL to Reports

- lib/compiled-config.js
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/modeler/Linting.spec.js
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
* adds `secrets` rule and adjusts error message
* adds `no-propagate-all-parent-variables` rule and adjusts error message
* adds `link-event` rule and adjusts error message
* updates development dependencies
Cf. https://github.com/camunda/bpmnlint-plugin-camunda-compat/blob/main/CHANGELOG.md#250
----
Related to https://github.com/camunda/camunda-modeler/issues/3793
> Add New Rules

- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
* update to bpmnlint-plugin-camunda-compat@2.7.1
* adjust `secrets` warning message
* `secrets` rule disabled for now
* adjust `no-loop` error message
> Disable `secrets` rule

- CHANGELOG.md
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/Linter.spec.js
- test/spec/modeler/Linting.spec.js
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
Depends on https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/140
> chore: rename `Camunda Platform` to `Camunda`

- lib/utils/error-messages.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/4020
Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/150
> feat: allow collapsed subprocess in 8.4

- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/properties-panel.spec.js
> feat(properties-panel): adjust FEEL error message

- CHANGELOG.md
- lib/compiled-config.js
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3945
> feat: support compensation

- lib/modeler/Linting.js
- test/spec/modeler/Linting.spec.js
- test/spec/modeler/linting-collaboration-cloud.bpmn
Related to https://github.com/camunda/camunda-modeler/issues/4158
> fix: show error for process refs

- karma.conf.js
- package-lock.json
- package.json
Related to https://github.com/camunda/camunda-modeler/issues/3613 this enables inclusive (joining) gateway for 8.6:
> Enable inclusive gateway (joining) for Camunda 8.6

- CHANGELOG.md
- package-lock.json
- package.json
This integrates the Performance improvements released with the latest compat release
> deps: update to bpmnlint-plugin-camunda-compat@2.21.1

- lib/compiled-config.js
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
Depends on https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/169
Related to https://github.com/camunda/camunda-modeler/issues/4386
> feat: lint `zeebe:bindingType`

- lib/compiled-config.js
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
Closes #113
We should get errors if version is less than 8.6 or if the priority isn't between 0 and 100 inclusive or a feel expression. That second error should be reflected in the properties panel.
> feat: implement `zeebe:PriorityDefinition` lint adjustments and props panel messages

- lib/utils/properties-panel.js
- test/spec/utils/properties-panel.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/4504
> fix: fix properties panel entry ID for user task `Priority`

- package-lock.json
- package.json
> Housekeeping (dependency bumps)

- CHANGELOG.md
- package-lock.json
- package.json
Related to https://github.com/camunda/camunda-modeler/issues/4562
> deps: update bpmnlint-plugin-camunda-compat to v2.26.1

- CHANGELOG.md
- lib/compiled-config.js
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
* Implementation: Zeebe user task is required with Camunda >=8.7
---
Related to https://github.com/camunda/camunda-modeler/issues/4610
> deps: update to `bpmnlint-plugin-camunda-compat@2.27.0`

- CHANGELOG.md
- lib/compiled-config.js
- lib/utils/error-messages.js
- lib/utils/properties-panel.js
- package-lock.json
- package.json
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
- deps: update dependencies
- feat: adjust missing task listener type message
- feat: support task listeners in properties panel
- feat: adjust missing task listener support message
related to https://github.com/camunda/camunda-modeler/issues/4590
> Support task listeners

- lib/utils/error-messages.js
- test/spec/utils/error-messages.spec.js
- test/spec/utils/properties-panel.spec.js
Related to [#4749](https://github.com/camunda/camunda-modeler/issues/4749)
Draft as it follow the other draft PR: https://github.com/camunda/linting/pull/125
> chore: update terminology to "camunda user task"

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/TASK.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
This adds missing PR and issue templates.
> docs: add PR and issue templates

- CHANGELOG.md
- package-lock.json
- package.json
This PR updates bpmnlint in order to fix the related Modeler issue.
Related to https://github.com/camunda/camunda-modeler/issues/4870
> deps: update to `bpmnlint@11.4.1`

- CHANGELOG.md
- package-lock.json
- package.json
Related to https://github.com/camunda/camunda-modeler/issues/4984
* `FEAT`: add Camunda 7.24 configurations ([camunda/bpmnlint-plugin-camunda-compat#200](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/200))
* `FIX`: allow disconnected elements and missing start/end events within ad-hoc subprocess ([bpmn-io/bpmnlint#181](https://github.com/bpmn-io/bpmnlint/pull/181))
* `DEPS`: update to `bpmnlint-plugin-camunda-compat@2.35.0`
* `DEPS`: update to `bpmnlint@11.4.2`
> Bumb linting deps

- CHANGELOG.md
- lib/compiled-config.js
- package-lock.json
- package.json
* `FEAT`: add `single-blank-start-event` to `correctness` ruleset ([bpmn-io/bpmnlint#187](https://github.com/bpmn-io/bpmnlint/pull/187))
* `FEAT`: allow to pass moddle extensions when validating via CLI ([bpmn-io/bpmnlint#62](https://github.com/bpmn-io/bpmnlint/issues/62), [bpmn-io/bpmnlint#8](https://github.com/bpmn-io/bpmnlint/issues/8), [bpmn-io/bpmnlint#188](https://github.com/bpmn-io/bpmnlint/pull/188))
* `CHORE`: update documentation link for C7 HTTL ([camunda/bpmnlint-plugin-camunda-compat#202](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/202))
* `DEPS`: update to `bpmnlint@11.6.0`
Related to https://github.com/camunda/camunda-modeler/issues/5044
Related to https://github.com/camunda/camunda-modeler/issues/4957
To ensure you provided everything we need to look at …
> Prepare v3.38.0

- CHANGELOG.md
- package-lock.json
- package.json
Update deps to get `parserDialect: camunda` integrated. As a result `backtick variable names` are now supported, cf:
Related to [camunda/modeler#4809](https://github.com/camunda/camunda-modeler/issues/4809)
> Update deps for feel parser dialect

- CHANGELOG.md
- package-lock.json
- package.json
Related to https://github.com/camunda/camunda-modeler/issues/5203
> deps: update to bpmnlint-plugin-camunda-compat@2.39.2

- package-lock.json
- package.json
update deps to get latest feel syntax support
> update feel deps
