package-lock.json
package.json

* didn't blow up in the past because these are dependencies of camunda-bpmn-js 🤡

fix: make bpmn-moddle and zeebe-bpmn-moddle production dependencies

---

lib/Linter.js
lib/utils/error-messages.js
lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/camunda-cloud-1-0-invalid.bpmn
test/spec/camunda-cloud-1-0-valid.bpmn
test/spec/camunda-cloud-1-1-invalid.bpmn
test/spec/camunda-cloud-1-1-valid.bpmn
test/spec/camunda-cloud-1-2-invalid.bpmn
test/spec/camunda-cloud-1-2-valid.bpmn
test/spec/camunda-cloud-1-3-invalid.bpmn
test/spec/camunda-cloud-1-3-valid.bpmn
test/spec/camunda-cloud-8-0-invalid.bpmn
test/spec/camunda-cloud-8-0-valid.bpmn
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/41
Closes #4 
Note this is added for all Camunda 8 versions, as it has been failing on deployment since the first supported Zeebe version (cf. https://github.com/camunda/linting/issues/4#issuecomment-1214751256).
----

Set error message for `duplicate-task-headers` rule

---

lib/utils/error-messages.js
lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/Linter.spec.js
test/spec/camunda-cloud-1-0-invalid.bpmn
test/spec/camunda-cloud-1-2-invalid.bpmn
test/spec/camunda-cloud-1-3-invalid.bpmn
test/spec/camunda-cloud-8-0-invalid.bpmn
test/spec/camunda-cloud-8-1-invalid.bpmn
test/spec/camunda-cloud-8-1-valid.bpmn
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

* error message in error panel adjusted
* error shown in properties panel for every extension property
We can only show errors for individual entries at the moment so the error is shown for the first entry of every extension property even though the extension property itself isn't allowed. In the future we could add error states for groups and list entries.
---
Depends on https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/43
Related https://github.com/camunda/product-hub/issues/335

feat: adjust error message for `zeebe:Properties`

---

lib/modeler/Linting.js
test/spec/modeler/Linting.spec.js

* add active state to linting
* only show annotations on selection changed if active
* be able to configure initial active state
---
Related to https://github.com/camunda/camunda-modeler/pull/3118#issuecomment-1240321426

fix: do not show annotations on update if inactive

---

lib/utils/error-messages.js
lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/modeler/Linting.spec.js
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

* depend on bpmnlint-plugin-camunda-compat v0.12.0
* adjust error message
* point to properties panel entry if condition is missing
---
Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/44
Related to https://github.com/camunda/camunda-modeler/issues/3083

Handle Inclusive Gateway Errors

---

lib/modeler/Linting.js
test/spec/modeler/Linting.spec.js

Due to the issue described in https://github.com/bpmn-io/properties-panel/pull/186#issue-1378022895 the properties panel isn't always focused on `showEntry`. To fix this issue a timeout is introduced to account for the async rendering of the properties panel. Once the issue has been fixed in the properties panel the timeout can be safely removed. In the meantime, nothing is going to change for users of `@camunda/linting` as the timeout is only used internally.
---
Related to https://github.com/bpmn-io/properties-panel/pull/186
Related to https://github.com/camunda/camunda-modeler/issues/3144

Use Timeout to Account for Async Rendering of Properties Panel

---

lib/utils/error-messages.js
lib/utils/properties-panel.js
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

We want the users to know that cron is available only in Camunda Platform 8.1 or newer.

chore: explicitly state platform support for cron time cycle

---

README.md

`activate` and `deactivate` were missing in the `README`.

docs: document #activate and #deactivate

---

lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/modeler/Linting.spec.js
test/spec/utils/properties-panel.spec.js

Currently, the Lint error takes precendent over the local error. Follow-up to fix it: https://github.com/bpmn-io/properties-panel/issues/190
Makes sure that FEEL lint errors map to the correct Properties panel entry
---
Related to https://github.com/camunda/linting/issues/22

feat(utils): make getEntryIds independent of error type

---

lib/utils/error-messages.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/81
----
Related to https://github.com/camunda/camunda-modeler/issues/3362

Allow Blank Error Catch Event in Camunda 8.2

---

CHANGELOG.md
lib/utils/error-messages.js
lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/modeler/Linting.spec.js
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

---
Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/86
Related to https://github.com/camunda/camunda-modeler/issues/3484

Lint `zeebe:TaskSchedule` Extension Elements

---

CHANGELOG.md
lib/utils/error-messages.js
lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

* update `bpmnlint-plugin-camunda-compat`
* remove legacy IDs (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/pull/931)
---
Requires https://github.com/bpmn-io/bpmn-js-properties-panel/pull/931

Ship `bpmnlint-plugin-camunda-compat@1.3` Rules

---

lib/utils/properties-panel.js
test/spec/utils/properties-panel.spec.js

related to https://github.com/camunda/camunda-modeler/issues/3357
The entry is used to select the input field in the properties panel. We want to be able to provide this information in the lint rule, as this might not be a static value (e.g. for element templates)

feat: allow custom entryIds

---

.eslintignore
.eslintrc
lib/Linter.js
lib/compiled-config.js
lib/utils/error-messages.js
lib/utils/properties-panel.js
lib/utils/version.js
package-lock.json
package.json
tasks/compile-config.js
test/spec/Linter.spec.js
test/spec/simple.bpmn
test/spec/utils/error-messages.spec.js
test/spec/utils/lint-helper.js
test/spec/utils/properties-panel.spec.js

* migrate to bpmnlint@9 and bpmnlint-plugin-camunda-compat@2
* show version hint for time cycle expression only if version older
---
Requires https://github.com/bpmn-io/bpmnlint/pull/113
Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/108
Related to https://github.com/camunda/camunda-modeler/issues/3709

Housekeeping

---

lib/modeler/LintingAnnotations.js

Related to https://github.com/camunda/modeler-design/issues/184 we want to ensure error annotations cannot hide, but remain visible on all zoom levels.

Scale annotations

---

CHANGELOG.md

* `FEAT`: improve overlay styles ([#70](https://github.com/camunda/linting/pull/70))
* `FEAT`: always show overlays and scale ([#72](https://github.com/camunda/linting/pull/72))
* `FEAT`: add execution platform and version to each report ([#66](https://github.com/camunda/linting/pull/66))
* `FIX`: fix time cycle error message ([#66](https://github.com/camunda/linting/pull/66))
* `FIX`: make root element selectable (by selecting nothing) ([#66](https://github.com/camunda/linting/pull/66))
* `FIX`: make missing time to live error selectable in properties panel ([#66](https://github.com/camunda/linting/pull/66))
* `CHORE`: create resolver using bpmnlint's compile-config helper ([#67](https://github.com/camunda/linting/pull/67))
* `DEPS`: update to `bpmnlint@9.2.0`
* `DEPS`: update to …

chore(CHANGELOG): v3.2.0

---

assets/linting.css

related to https://github.com/camunda/camunda-modeler/issues/3754
Tested via local linking in the modeler:

fix(css): explicitly set box-sizing

---

assets/linting.css
lib/modeler/LintingAnnotations.js

Required by https://github.com/camunda/camunda-modeler/issues/3762
----
As stable as it gets :see_no_evil:

fix: use stable annotation size

---

README.md
lib/Linter.js
package-lock.json
package.json
test/spec/Linter.spec.js

this requires a new configuration option `type = platform` to be set
Integration into the modeler looks like this: https://github.com/camunda/camunda-modeler/pull/3878
related to https://github.com/camunda/camunda-modeler/issues/3853

fix(Linter): correctly parse C7 XML 

---

lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel-info.bpmn
test/spec/utils/properties-panel.spec.js

Depends on https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/137
Related to https://github.com/camunda/camunda-modeler/issues/3834

Only Display Errors in Properties Panel

---

CHANGELOG.md

* `FEAT`: allow signal boundary, intermediate catch, and signal start events in sub-processes ([#86](https://github.com/camunda/linting/pull/86))
* `FEAT`: enable `secrets` rule for Camunda 8.3 ([#86](https://github.com/camunda/linting/pull/86))
* `FIX`: only display errors in properties panel ([#86](https://github.com/camunda/linting/pull/86))
* `DEPS`: update to `bpmnlint-plugin-camunda-compat@2.8.0`

chore(CHANGELOG): update to v3.8.0

---

CHANGELOG.md
lib/compiled-config.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

* `FEAT`: allow `formKey` and `formId` starting with v8.3 when linting start event forms ([#149](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/149))
* `FIX`: differentiate between desktop and web modeler when linting user task forms ([#149](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/149))
* `DEPS`: update to `bpmnlint-plugin-camunda-compat@2.12.0`
---
Related to https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/147

Prepare v3.11 Release

---

lib/utils/documentation.js
lib/utils/properties-panel.js
test/spec/modeler/Linting.spec.js
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/4062

feat(platform): make HTTL an `info` hint

---

lib/Linter.js
lib/plugins/bpmnLintPlugin.js
lib/plugins/index.js
test/spec/Linter.spec.js
test/spec/simple-no-di.bpmn

related to https://github.com/camunda/camunda-modeler/issues/4277
I decided to add it in `@camunda/linting` directly instead of adding the plugin to the camunda modeler, so the linting between desktop and web modeler stays consistent

feat: enable `bpmnlint/no-bpmndi` for all profiles

---

lib/utils/properties-panel.js
test/spec/utils/properties-panel.spec.js

feat(properties-panel): show supported version

---

CHANGELOG.md
lib/compiled-config.js
lib/utils/error-messages.js
lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

- deps: update dependencies
- feat: adjust duplicated execution listeners message
- feat: adjust missing execution listener type message
- feat: support execution listeners in properties panel
- feat: adjust missing execution listener support message
Related to https://github.com/camunda/camunda-modeler/issues/3951

Support execution listeners

---

lib/compiled-config.js
lib/utils/error-messages.js
lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js
test/spec/utils/lint-helper.js
test/spec/utils/properties-panel.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/4480

Support `zeebe:VersionTag` and `zeebe:versionTag` errors

---

lib/compiled-config.js
lib/utils/error-messages.js
lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

Integrates fix for https://github.com/camunda/camunda-modeler/issues/4519 and handles the changed lint errors.
---
Related to https://github.com/camunda/camunda-modeler/issues/4519
Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/174

feat: update `no-version-tag` rule and add `version-tag` rule

---

CHANGELOG.md
lib/compiled-config.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

This updates the compat plugin, cf. https://github.com/camunda/bpmnlint-plugin-camunda-compat/blob/main/CHANGELOG.md#2281

deps: update to `bpmnlint-plugin-camunda-compat@2.28.1`

---

CHANGELOG.md
lib/compiled-config.js
lib/utils/documentation.js
lib/utils/error-messages.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js
test/spec/utils/properties-panel.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/4690
Needs to integrate https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/183/commits first because the rule currently doesn't exist

Mark job worker-based user task managed by Camunda as deprecated

---

.github/workflows/CI.yml
CHANGELOG.md
package-lock.json
package.json
test/spec/utils/error-messages.spec.js

* deps: update to `bpmnlint-plugin-camunda-compat@2.30.0`
* feat: allow task listeners in Camunda 8.8 or newer
Related to https://github.com/camunda/camunda-modeler/issues/4799

Allow task listeners in Camunda 8.8 or newer

---

CHANGELOG.md
package-lock.json
package.json

Support `bpmm:AdHocSubProcess` for Camunda 8.7 and newer.
Related to https://github.com/camunda/camunda-modeler/issues/4739

feat: support `bpmn:AdHocSubProcess`

---

CHANGELOG.md
lib/utils/properties-panel.js
package-lock.json
package.json
test/spec/utils/properties-panel.spec.js

Adds integration for linting rules added in https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/196
Related to https://github.com/camunda/camunda-modeler/issues/4850

Support for `completionCondition` and `cancelRemainingInstances` on ad-hoc subprocess

---

lib/utils/error-messages.js
package-lock.json
package.json
test/spec/utils/error-messages.spec.js

Related to camunda/camunda-modeler#4859
Only not Allow BoundaryEvent on Tasks (via dep update) and adjust the related error message

Not allow escalationBoundaryEvents on tasks

---

lib/utils/error-messages.js
test/spec/utils/error-messages.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/4872
By limiting the formId message adjuster to only trigger when formId is required, now the proper versionTag adjuster works

Only adjust message when value is required
